url: 'mongodb://localhost:27017'
username: admin
password: '90054'
db_name: new_final_result
main_collection_name: all_instance
job_index_collection_name: job_index
job_record_collection_name: job_record
job_record_backup_collection_name: job_record_backup

